- tweets/after_d1.tweet
feel free to change before posting :)
> draft for post day1 tweet

- tweets/before_d2.tweet
Just in case no one is more creative ;)
> A tweet for tuesday morning

- tweets/after_morning_d2.tweet
> Morning session tweet

- tweets/after_first_talks.tweet
Again, please update with more creative stuff. 
And check that the right people are linked. 
Should we actually do that? Linking people? Tweeting about specific talks?
> could be posted after talks session?

- tweets/podcast_April21
Suggestion for a tweet about Peters podcast.
Please adjust as you see fit :)
> sharing code for thought podcast link

- tweets/podcast_April21.tweet
- tweets/podcast_sharing.tweet
> Podcast sharing - This time with extension

- tweets/announce-2021-june-unconference.tweet
Closes #15 
Feel free to edit, improve or completely rewrite.
> Announce the Nordic-RSE 2021 unconference

- tweets/unconference20210615.tweet
Please feel free to edit and improve.
> Week 24 announcement for 2021 unconference

- tweets/unconference2021-4th-invited-talk.tweet
Please fact-check and improve. @annefou for info
> tweet about 4th talk

- tweets/unconference2021-first-day-live.tweet
Announcement during first day of the 2021 unconference.
As always, feel free to edit and improve.
> Tweet for first unconference day going live

- tweets/unconference_day2.tweet
> starting day 2 suggestion

- tweets/seminar_announce.tweet
A suggestion for a tweet to be tweeted this week (week 32)
@lucaferranti do you have twitter or anything else you'd like linked here?
please all check and edit :)
Suggestion to wait until we have a new generic twittercard (working on it).
> Seminar announcement tweet suggestion

- tweets/seminarday.tweet
as usual please rewrite/add/edit :)
> suggestion for tweet about soon starting seminar

- tweets/youtube_announce.tweet
Please add #'s and rewrite to your liking :)
Again this is just to get the ball rolling, I do not mind at all if someone rewrites it completely, that's why we tweet together and not alone, right? ;)
> suggestion for announcing recordings on youtube

- tweets/rustandpython.tweet
should only be posted AFTER https://github.com/nordic-rse/nordic-rse.github.io/pull/279 is merged :)
as usual feel free to edit/rewrite
> Suggestion for Rust&Python savethedate tweet

- tweets/rustandpython_onseminarday.tweet
As usual: Feel free to edit/rewrite :)
Do not merge before tomorrow! (it mentiones today, which means tomorrow which would be weird to post any other day but tomorrow ;) )
> suggestion for tweet for  seminar announcement tomorrow morning

- tweets/210916_video.tweet
please feel free to edit directly if you have better idea for text ( I do not believe that I am the right person for this job) :) 
As usual this is more to initiailize the posting 
Also, I started adding dates to the tweet filenames to not have to come up with new unique text for every tweet
> announcing Lucas video on youtube

- tweets/SSI-fellowship-2021.tweet
I suggest we send the Julia course tweet today and this one tomorrow.
> SSI-fellowship-2021

- tweets/2021-11-survey-blog-post.tweet
As usual, edit/suggest freely.
> tweet about survey blog post

- tweets/2022-01-survey-reminder.tweet
> RSE survey 2021 reminder

- tweets/2022-01-20-seminar.tweet
> Reduce the number of characters

- tweets/2023-May-seminar-series.tweet
Since I'm incapable of doing a good job the first time I try, here's the shortened version of the tweet.
> Shortened tweet
